### ISSUE TITLE
Conflict with id field when it is not used as hash key 

### ISSUE THREAD

**Issue by BilalBudhani** [OceanDev/ocean-dynamo#20]
Hi, 
I'm using this gem in my project. So, the scenario is we have migrated our table from previous database where `id` was a auto generated key. After migrating our table to DynamoDB we no longer use `id` key instead we use `uid` (which is unique key generated by us). But we've to keep `id` field in the table to support legacy codebase. 

Now the problem is whenever I try to set `uid = some value` then, `id` field gets the same value and visa versa. I cannot set the same values for both the fields. 

What are your thoughts on this?

Also, Thanks for making this great gem.

**Comment by PeterBengtson** [comment]
What does the mapping from id to uid? There's no such logic in the gem.

**Comment by PeterBengtson** [comment]
Ah, I think I understand what you mean. You've declared uid to be the index field for your DynamoDB table, and the name of the index field is always aliased to id.

In that case I'd simply rename the id attribute to old_id. Depending on how it is done, you might need to it in three steps: 1: loop through each record of your table and set the new attribute, 2: change the table definition by removing the id field, 3: loop through the table again just to save the records again in order to remove the id value.

**Comment by BilalBudhani** [comment]
@PeterBengtson thanks for responding back. Actually, I cannot get rid or change the attribute name for `id` field. It is being used by other legacy codebase which is hard to change. That's the reason we're rewriting it in a Service oriented architecture. I've forked the gem and patched it to work with my scenario.

**Comment by PeterBengtson** [comment]
The reason that the index attribute is aliased to id is that it’s needed in some places for ActiveRecord compatibility - some code relies on the index attribute being named ”id” and nothing else. It might be that you won’t be affected by this, or that your usage pattern doesn’t need ActiveRecord compatibility. Just watch out for any unwanted side effects.

	/ Peter

**Comment by BilalBudhani** [comment]
I understand the purpose of aliasing index attribute to id. Even my goal is to stay as close as possible with ActiveRecord patterns. Thanks for the heads up.
