### ISSUE TITLE
Support for devise gem

### ISSUE THREAD

**Issue by singerdmx** [OceanDev/ocean-dynamo#29]
By using devise gem, class User is subclass of ActiveRecord and migration to ocean dynamodb does not work.

**Comment by singerdmx** [comment]
https://rubygems.org/gems/devise/versions/3.5.2

**Comment by PeterBengtson** [comment]
You're not really giving me much to work from here, but ocean-dynamo isn't
intended to be 100 percent plug in compatible with ActiveRecord. The noSQL
paradigm used by DynamoDB is quite different from the SQL one in
ActiveRecord. In moving an ActiveRecord table to DynamoDB, regardless of
whether you're using ocean-dynamo or any of the other common DynamoDB
interface gems, you should examine your database schema to see what fits
noSQL and what doesn't. Some things will have to be reworked, but this is
not due to ocean-dynamo but to DynamoDB and the transition to noSQL.

Also, ocean-dynamo as yet only supports the has_many and belongs_to
relations. That's by far the most common one, and it probably covers 90
percent of all use cases, but if your ActiveRecord table has other
relations than that, you might want to wait a little. Work is in progress
on the has_and_belongs_to_many relation; this requires a major internal
reorg of the code. The rewrite will bring ocean-dynamo even close to the
ActiveRecord internal structure, but in the meantime you'll have to use
direct finds to implement other relation types.

But perhaps I'm misunderstanding you, and the problem you're having is a
simpler one. But in that case I need more data to go on.

**Comment by singerdmx** [comment]
Thanks!
I guess I am looking at https://github.com/Veraticus/Dynamoid and for devise, they have:
https://github.com/macteo/devise-dynamoid
https://github.com/deekshithmarla/devise-dynamoid
https://github.com/vinaycyadav/dynamoid-devise

Ruby on Rails usually uses Devise and I am hoping ocean-dynamo can provide such support even as a separate gem. Thanks!
