### ISSUE TITLE
Model.count doesn't function as expected

### ISSUE THREAD

**Issue by will3216** [OceanDev/ocean-dynamo#30]
In my local dev environment I am seeing this behavior:

```
> Model.all.count
=> 201
> Model.count
=> 0
```

**Comment by PeterBengtson** [comment]
Hey, Will. The difference is normal and expected, and actually tested for in the RSpec test suites. 

Check the DynamoDB documentation, you'll find that the count for the entire collection is updated by AWS only every 6 hours. That's the figure <tt>Model.count</tt> returns. 

On the other hand, <tt>Model.all.count</tt> works by first retrieving all <tt>Model</tt> instances and then counting the number of items obtained. Unless you know that your DynamoDB is very small and your access quota are set high enough, this is extremely wasteful and should be avoided, as all you're doing with the retrieved data is counting it, then discarding it. If your tables are large, this will consume quota points in an unacceptable way. It will also fill up your memory. 

Moreover <tt>Model.all.count</tt> is also subject to the effects of _eventual consistence_, as are all read and write operations in DynamoDB. You can override this to get strong consistency, but this will of course cost you double quota points.

Real-time counts and scalability really don't go together. What you do is to engineer your application never to need or use them, or compute them when throttling is acceptable. Use the iterators defined in <tt>ocean-dynamo</tt> to process instances in chunks rather than read all of them into memory; set up your schema so that eventual consistence is acceptable, avoid scans, and so forth.

So the behaviour you see is intentional and expected, and I'm closing this ticket. Thanks for reporting it, though!

**Comment by will3216** [comment]
Cool, totally makes sense. I was actually pointing at my aws dynamo and not my local which explains the discrepancy. This gem is awesome by the way! Thanks for the response
